id: PA190CCF5
initial_creation_type: ocr
source_metadata:
  volumes:
    43d8efe0fb2547cd8b32ebc013c7a1ac:
      base_file: v042.txt
      image_group_id: I1PD95887
      title: ''
      total_pages: 1712
      volume_number: 42
